source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftDefaults_Example' do
  pod "SwiftDefaults", :path => "../"

  target 'SwiftDefaults_Tests' do
    inherit! :search_paths
    pod "SwiftDefaults", :path => "../"

    pod 'Quick', '~> 0.8.0'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
